//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.17 at 10:58:47 AM CEST 
//


package my.sandbox.pf4j.spring.xml.modules;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the my.sandbox.pf4j.spring.xml.modules package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: my.sandbox.pf4j.spring.xml.modules
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FxPlugin }
     * 
     */
    public FxPlugin createFxPlugin() {
        return new FxPlugin();
    }

    /**
     * Create an instance of {@link PluginInfo }
     * 
     */
    public PluginInfo createPluginInfo() {
        return new PluginInfo();
    }

    /**
     * Create an instance of {@link RestModule }
     * 
     */
    public RestModule createRestModule() {
        return new RestModule();
    }

}
