apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test-2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /pod2
            backend:
              serviceName: kube-pod-2
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kube-pod-2
spec:
  selector:
    app: kube-pod-2
  ports:
    - protocol: TCP
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-pod-2
spec:
  selector:
    matchLabels:
      app: kube-pod-2
      tier: kube
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-pod-2
        tier: kube
    spec:
      containers:
        - name: kube-pod-2
          image: jvaca92/kube-pod-2:latest
          imagePullPolicy: Never
          ports:
           - containerPort: 8080